name: laravel-api-dev

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:8000" # Mapea el puerto para Postman (Local:Contenedor)
    volumes:
      - .:/var/www/html
    networks:
      - web-stack
    environment:
      - .env
    # Esto asegura que si el comando falla (por falta de vendor), el contenedor no muera
    stdin_open: true 
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

networks:
  web-stack:
    external: true